replicaCount: 1

image:
  repository: ghcr.io/caioricciuti/ch-ui
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 5521
  annotations: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: ch-ui.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

config:
  clickhouse:
    # Option 1: Provide values directly
    url: "http://clickhouse:8123"
    user: "default"
    password: ""
    useAdvanced: false
    # Option 2: Use an existing secret
    # If existingSecret is set, it will override the above values
    existingSecret: ""
    # Keys in the existing secret (defaults shown)
    existingSecretKeys:
      password: "VITE_CLICKHOUSE_PASS"
  app:
    basePath: ""
    requestTimeout: 30000
    distributed: false

env: []

envFrom: []

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
